### ISSUE TITLE
Decode value with leading-dot key

### ISSUE THREAD

**Issue by dispatchqueue** [utahiosmac/Marshal#102]
How to get value for key ".tag" from this JSON:

    {
        ".tag": "test"
        "name": "something"
    }

Marshal splits the key by `.`, so `object.value(for: ".tag")` returns nil because `tag` key is not found.

**Comment by jarsen** [comment]
Good question... I don't think this case has been considered, but this seems to be pretty atypical JSON. Supporting this case would be difficult without removing the keypath support.

Out of curiosity, _why_ is your API doing this? Given that JSON is usually supposed to be easily translated and used as a Javascript object where it's nice to be able to use the `.` operator having keys with periods in it seems undesirable.

My suggestion for a workaround would be to manipulate the dictionary _before_ you pass it in. i.e., when you get it back from the network, do something like:

```swift
foo["tag"] = foo[".tag"]
let myObject = try MyObject(object: foo)
```

**Comment by dispatchqueue** [comment]
Thanks @jarsen.

Dropbox API is doing like that: https://www.dropbox.com/developers/documentation/http/documentation#files-get_metadata

Other JSON libraries are using this keypath syntax to access nested data: `object.value("user", "email", "person")`. I think that syntax is better and less error-prone than using `.`.

**Comment by jarsen** [comment]
That's a great suggestion, and one I think definitely worth exploring.

**Comment by jarsen** [comment]
I'm going to reopen this because I feel like that's probably worth implementing.

**Comment by dispatchqueue** [comment]
Great! Thanks @jarsen.
