### ISSUE TITLE
Error building Marshal using Carthage

### ISSUE THREAD

**Issue by natebird** [utahiosmac/Marshal#105]
I'm updating my app to Swift 3.1 and I ran `carthage update` after installing Xcode 8.3 and swift 3.1.

While building Marshal if fails with the following: `<unknown>:0: warning: argument unused during compilation: '-iapinotes-modules /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/arm64'`

I don't think it is Marshal specific because I checked out the Marshal repo and it builds fine. However, this is the only framework where I get this error. Any ideas of how I can work around this warning? Internet search says to pass `-Qunused-arguments` but is that possible with Carthage?

**Comment by jarsen** [comment]
Hm. Not sure. I'll have to look into it when I have some more time. In the mean time if you figure it out plz let me know :)

**Comment by jarsen** [comment]
Are you still having problems with this, @natebird? Or did you ever get it figured out?

**Comment by natebird** [comment]
I haven't figured it out. But I also haven't put any more time into it. When I try it again then I'll report back. 

Closing for now. I'll reopen if it is still and issue.
