### ISSUE TITLE
Int64 Extracted from NSNumber?

### ISSUE THREAD

**Issue by brianmullen** [utahiosmac/Marshal#12]
@jarsen @bwhiteley 
Is there a reason why the `Int64` is being extracted from an `NSNumber`? The underlying type for a Swift `Int` is an `Int64` and so you should be able to just extract and cast from an `Int`

**Comment by bwhiteley** [comment]
@psychoticidiot : https://github.com/bwhiteley/JaSON/pull/2
There was a unit test added for it as well. It was kind of puzzling. 
Ask @derrh for details.
