### ISSUE TITLE
New release for swift 4

### ISSUE THREAD

**Issue by mbesnili** [utahiosmac/Marshal#125]
Could you please release a version with swift 4.0 ? 

Thank you.

**Comment by safety97** [comment]
Please release a version for swift 4.0,  
Xcode 10.2 does not accept dependencies with a swift version less than 4.0.

Thank you in advance.

**Comment by bwhiteley** [comment]
Any objection to going straight to swift 5.0?

**Comment by bwhiteley** [comment]
Never mind going straight to swift 5.  Release 1.2.7 is for Swift 4.0. The tests pass with Xcode 10.2. 
The next release will be Swift 5.
