### ISSUE TITLE
Push podspec to Cocoapods trunk

### ISSUE THREAD

**Issue by olejnjak** [utahiosmac/Marshal#129]
Hi, would it be possible to push the podspec to Cocoapods trunk? Last version there is 1.2.4. Thanks :-)

**Comment by bwhiteley** [comment]
@bjarkehs , @brianmullen Could one of you take care of this? Looks like I don't have permission.

**Comment by bjarkehs** [comment]
Yes. Sorry I didn't notice this until now. It's now been pushed.
I can give you permission, @bwhiteley, if you want.

**Comment by olejnjak** [comment]
Thanks guys 👍 🙂
