### ISSUE TITLE
Add a protocol so we can serialize a data type into an Object

### ISSUE THREAD

**Issue by brianmullen** [utahiosmac/Marshal#14]
We should add a protocol to serialize data types into an `Object`.

Something like: 

```
public protocol ObjectRepresentable
{
     var objectValue: Object { get }
}
```

**Comment by jarsen** [comment]
Agreed. I've been trying to think of good names for this protocol for a while. I actually find `ObjectConvertible` a little confusing—it's not immediately clear to me if it converts into an `Object`, or can be converted _from_ an `Object`. Same with `ObjectRepresentable` I wonder if we want to move towards something more along the lines of `Codable` and `Decodable`? Or `Marshalable` and `Demarshalable`. Although I'm not sure those are immediately clear either. Or real words.

**Comment by bwhiteley** [comment]
I found a number of other projects using `Marshallable` and `Unmarshallable`. 
I like it.

**Comment by brianmullen** [comment]
I am fine with either one. However, if we use `Codable` and  `Decodable`, I think more people would know what it is since that follows similar naming with what apple uses.

**Comment by jarsen** [comment]
I'm fine with either as well. `Marshallable` does fit better with the lib name though.
