### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by JetForMe** [utahiosmac/Marshal#146]
Is this project dead? I really hope not. I prefer it to the "official" way of marshaling objects, but I'd love to get some new features.

**Comment by bwhiteley** [comment]
@JetForMe not entirely dead. In hindsight we should have given commit access to basically every contributor along the way to maximize the possibility that the project lives on even after some original authors moved on. 

The project is still used in multiple shipping apps written by various people. It arguably has better ergonomics than `Codable` in some ways. It can also still be quite a bit faster than `Codable`. 

What features do you have in mind?

**Comment by JetForMe** [comment]
Glad to hear it! I agree the ergonomics are better.

By chance I happened to notice something that might be the feature I wanted: Array unmarshaling with `discardingErrors`.
