### ISSUE TITLE
Expose `anyForKey` in the dictionary extension

### ISSUE THREAD

**Issue by brianmullen** [utahiosmac/Marshal#18]
In case there are situations where another dataType comes along that doesn't fall under our current dictionary extension, it would be helpful for users to utilize the existing code to write their own dictionary extensions to handle that dataType. For example, we don't currently support the Swift `Set` type and so users are left to manually extract as an `Array` and then pass it to the `Set` constructor.

We should change `private func anyForKey` to `public func anyForKey`

**Comment by jarsen** [comment]
Interesting. I can see a case for this.

On a side note, _should_ we add support for `Set<T>`?

**Comment by brianmullen** [comment]
I consider Array, Dictionary and Set to be the core Swift collection types and so I think we should add support for it.

**Comment by jarsen** [comment]
I agree, I've opened up a separate issue #19 to deal with `Set`.

If you send a PR for changing `anyForKey` visibility I would be happy to merge it.
