### ISSUE TITLE
the name is not elegant !

### ISSUE THREAD

**Issue by OHeroJ** [utahiosmac/Marshal#67]
i like the code design, but not like the name "UnmarshalingWithContext " for class

**Comment by jarsen** [comment]
Hey, thanks for the feedback. Do you have a suggestion?

**Comment by dlbuckley** [comment]
I must admit I agree with @OHeroJ here. Sorry to quote a dictionary on the word 'marshal', but:

> • assemble and arrange (a group of people, especially troops) in order: the general marshalled his troops.
> • bring together and arrange in order (facts, ideas, objects, etc.): he paused for a moment, as if marshalling his thoughts.
> • position (rolling stock) in the correct order.

So to 'Unmarshal' something kind of means to 'mess up order', which isn't happening in this case as its bringing order to to the chaos of JSON.

Although saying this I'm not sure what the suggestion should be for a replacement as it's quite a hard name to use in this context.

**Comment by brianmullen** [comment]
@dlbuckley that is the definition of the English word. In the context of computer science, refer to this definition:
https://en.m.wikipedia.org/wiki/Marshalling_(computer_science)

From what I understand, the comment from @OHeroJ is suggesting that the protocol "UnmarshalingWithContext" is poorly named and not the entire framework.

**Comment by jarsen** [comment]
@OHeroJ if you can come up with a more elegant name, I'd love to hear it! Until then, I'm going to go ahead and close out this issue.

**Comment by dlbuckley** [comment]
@psychoticidiot point taken :)
