### ISSUE TITLE
Support for discarding invalid objects in arrays

### ISSUE THREAD

**Issue by jgrandelli** [utahiosmac/Marshal#71]
https://github.com/utahiosmac/Marshal/issues/68 Allows arrays of optionals so objects that fail to initialize will be result in optionals in the array. This would add functionality to drop nil values from arrays. Both this and https://github.com/utahiosmac/Marshal/issues/68 would enable the ability to serialize data that can be and discard that which can't be instead of throwing it all out. Addressing these two issues would add great flexibility to parsing arrays of objects while not breaking current behavior.

**Comment by jarsen** [comment]
Fixed
