### ISSUE TITLE
Is it possible to unmarshal a [String: AnyObject] directly without calling .value()?

### ISSUE THREAD

**Issue by econner** [utahiosmac/Marshal#75]
I, unfortunately, have some API endpoints that return responses which are objects that I would like to unmarshal.  So say I get something that's a user object back:

`
{"username": "eric", "id": 1}
`

From my API, I get this value as a [String: AnyObject], so there is no opportunity to call `.value()` on it.  I simply want to convert it directly to an object.

Is the only option to re-wrap the [String: AnyObject] in another [String: AnyObject]?  Or can I somehow unmarshal a [String: AnyObject] directly?

**Comment by bwhiteley** [comment]
@econner If `User` conforms to `Unmarshaling` and you already have a dictionary, you can call the initializer. 
`let user = try User(object: dictionary)`

**Comment by econner** [comment]
Thanks!
