### ISSUE TITLE
Add a protocol so we can update/configure existing objects.

### ISSUE THREAD

**Issue by brianmullen** [utahiosmac/Marshal#8]
We already have support to create new objects and so it seems logical that we add a protocol for updating/configuring existing objects.

Something like the following:

```
public protocol ObjectConfigurable
{
     func configure( object: Object )
}
```

**Comment by jarsen** [comment]
I think this is a good idea, especially since if you want to have Core Data models, this is the only way to do it. I personally like the name `update`, but I'm open to whatever.

**Comment by brianmullen** [comment]
I am ok with either name. When I added that protocol to `Extractable` I chose to go with `configure` because it made more sense in how I was using it.

**Comment by jarsen** [comment]
@psychoticidiot how about something like `Remarshallable` to go along with `Marshallable` and `Unmarshallable`?
