### ISSUE TITLE
no pod ??

### ISSUE THREAD

**Issue by maryamfekri** [utahiosmac/Marshal#88]
please provide pod for your mapper project 🙏🏻

**Comment by jarsen** [comment]
There is a podspec. What else is needed?

**Comment by soloy** [comment]
[Podfile](https://github.com/utahiosmac/Marshal/blob/master/Marshal.podspec) is still at 1.0.1 and latest release is 1.2. Could this be updated?

**Comment by maryamfekri** [comment]
I didn't see you pod name in description of Marshal repo, then I though it might not have pod. 
so I think you should edit your description and add the pod name AND also update your pod to latest version please.

**Comment by jarsen** [comment]
I don't use cocoapods, so have relied on help up to this point. If you would like to submit a PR that would be much appreciated!

**Comment by jarsen** [comment]
That is, unless there is something else you would like updated, besides the version number.

**Comment by jarsen** [comment]
I've gone ahead and updated the version number to `1.2.1`.

The pod already has a name, unless I'm misunderstanding.

I'm going to go ahead and close this issue, but am willing to reopen if I missed something. Thanks, you two!
