### ISSUE TITLE
Podspec update as part of release cycle

### ISSUE THREAD

**Issue by nickvelloff** [utahiosmac/Marshal#94]
Thanks for the great lib. I removed another older, less performant lib that served us well for a long time to move to this much lighter and flexible approach... and it's great.

Is there any way we can get the `Podspec` version updates for releases? I use this in a stand alone http client dynamic lib. Would be great to get the fixes when you release them 😅

**Comment by jarsen** [comment]
Glad you like it! I'll try to remember 😋. I just forget because I don't use cocoapods. If I forget PRs are welcome of course.

**Comment by nickvelloff** [comment]
@jarsen great thanks... And happy to PR as well. I won't be able to push the spec but to trunk, but I'll get the rest lined up
