### ISSUE TITLE
Cocoapods (Actually pushing to Trunk)

### ISSUE THREAD

**Issue by bjarkehs** [utahiosmac/Marshal#95]
Hi,

I see a lot of issues around Cocoapods right now, and it stems from people not actually being able to access the podspec, without specifying the git url. In order to fix this then @psychoticidiot needs to run `pod trunk push Marshal.podspec`.

This will release version 1.2.3 to cocoapods.org, and can then be found with a simple `pod 'Marshal', '~> 1.2'.

Right now you have to do: `pod 'Marshal', :git => 'https://github.com/utahiosmac/Marshal.git'`.

I hope this clarifies things. If you want, you can add me as a maintainer of the pod, and I'll make sure it gets updated on Trunk.

**Comment by jarsen** [comment]
Cool. What does making you a maintainer entail?

**Comment by bjarkehs** [comment]
Well, it's more of a contributor of the pod on Cocoapods. Which would allow me to update the podspec.

**Comment by jarsen** [comment]
Right, so what does that require? How does one do that and where?

**Comment by bjarkehs** [comment]
One of the contributors of the pod, i.e. Brian Mullen has to run an adding command. You do it by getting cocoapods on your machine, signing in, and then running `pod trunk add-owner Marshal <email>`

**Comment by brianmullen** [comment]
@bjarkehs I added you as an owner of the pod so that you can manage it.

**Comment by bjarkehs** [comment]
@psychoticidiot Thanks!

I have now pushed the newest podspec.
