### ISSUE TITLE
ERR: Pod No such Module

### ISSUE THREAD

**Issue by ghost** [utahiosmac/Marshal#97]
Hello together,

everythink worked fine. Then I added an other pod and deleted it again. And now I always get following error while importing

../ViewController.swift:11:8: No such module 'Marshal'

I also deintegrate  and did pod init on my project. I still get the error.

What could be the Problem?
Do you have any suggestions for me to check?

Kind Regards
Alexander Niebuhr

**Comment by bjarkehs** [comment]
Did you perform a clean and also remove derived data?

**Comment by ghost** [comment]
@bjarkehs Yeah I did a full clean and removed the derived data. :/

**Comment by ghost** [comment]
I did fix the Problem with reopening a complete new Xcode Project and copying my Code 1 to 1 over. It worked, i also saw some Cocoapods Architecture Warnings in my Log, so this might be related to this issue. However, for me it's always a bit complicated to work with Cocoapods :)

Anyways, feel free to close this issue. 

Kind Regards
Alex
