### ISSUE TITLE
Can someone push the Podspec please?

### ISSUE THREAD

**Issue by nickvelloff** [utahiosmac/Marshal#98]

**Comment by jarsen** [comment]
@bjarkehs would u take care of this when you have some time? thank you :)

**Comment by bjarkehs** [comment]
Just waiting for #99

**Comment by jarsen** [comment]
Should be good to go @bjarkehs

**Comment by bjarkehs** [comment]
@jarsen Everything should be pushed now :)

**Comment by nickvelloff** [comment]
Thanks @bjarkehs !
